.PHONY: help upgrade requirements clean quality \
	requirements-test coverage pii_check \
	compile_translations dummy_translations extract_translations \
	fake_translations test test-python \
	test-js quality-python quality-js

.DEFAULT_GOAL := help

define BROWSER_PYSCRIPT
import os, webbrowser, sys
try:
	from urllib import pathname2url
except:
	from urllib.request import pathname2url

webbrowser.open("file://" + pathname2url(os.path.abspath(sys.argv[1])))
endef
export BROWSER_PYSCRIPT
BROWSER := python -c "$$BROWSER_PYSCRIPT"

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '*.pyc' -o -name '*.pyo' -o -name '*~' -delete
	rm -fr build/ dist/ *.egg-info
	rm -rf pii_report

upgrade: ## update python dependencies
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

requirements: ## install development environment requirements
	uv sync --group dev

requirements-test: ## install requirements for running tests
	npm install -g gulp-cli
	uv sync --group test

install: requirements
	./manage.py migrate --settings=test_settings
	npm install

coverage: clean ## generate and view HTML coverage report
	py.test --cov=edx_proctoring --cov-report html --ds=test_settings
	$(BROWSER) htmlcov/index.html

pii_check: ## check for PII annotations on all Django models
	DJANGO_SETTINGS_MODULE=test_settings \
	code_annotations django_find_annotations --config_file .pii_annotations.yml --lint --report --coverage

quality-js: lint-js

quality-python: ## Run python linters
	pylint edx_proctoring
	pycodestyle edx_proctoring
	isort --check-only --diff edx_proctoring manage.py

quality-rst: ## validate rst files
	rstcheck -r --report-level warning .

quality: quality-js quality-python quality-rst ## Run linters

test-python: clean ## run tests in the current virtualenv
	python -Wd -m pytest --cov=edx_proctoring --cov-report=html --ds=test_settings -n 3

test-js:
	OPENSSL_CONF=/dev/null gulp test

lint-js:
	./node_modules/.bin/eslint --ignore-pattern 'edx_proctoring/static/index.js' --ext .js --ext .jsx .
	./node_modules/.bin/eslint --config .eslintrc.worker.json 'edx_proctoring/static/index.js'

diff_cover: test
	diff-cover coverage.xml

## Localization targets

extract_translations: ## extract strings to be translated, outputting .po files
	cd edx_proctoring && django-admin makemessages -l en -v1 -d django
	cd edx_proctoring && django-admin makemessages -l en -v1 -d djangojs

compile_translations: ## compile translation files, outputting .mo files for each supported language
	cd edx_proctoring && django-admin compilemessages

detect_changed_source_translations:
	cd edx_proctoring && i18n_tool changed

validate_translations: ## Test translation files
	cd edx_proctoring && i18n_tool validate -v

dummy_translations: ## generate dummy translation (.po) files
	cd edx_proctoring && i18n_tool dummy

install-js: ## install JavaScript dependencies
	npm install

build_dummy_translations: extract_translations dummy_translations compile_translations ## generate and compile dummy translation files

check_translations_up_to_date: build_dummy_translations detect_changed_source_translations ## validate translations

test: test-python test-js ## run tests
