[tox]
envlist = quality, django{42,52}, pii_check, version_check, translations-django{42,52}
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups =
    django42: django42
    django52: test
allowlist_externals = make
commands =
    make test-python

[testenv:js_tests]
runner = uv-venv-lock-runner
dependency_groups = dev
allowlist_externals =
    npm
    make
commands =
    npm install -g gulp-cli
    npm install
    make test-js

[testenv:js_lint]
runner = uv-venv-lock-runner
dependency_groups = dev
allowlist_externals =
    npm
    make
commands =
    npm install -g gulp-cli
    npm install
    make lint-js

[testenv:rst_validation]
runner = uv-venv-lock-runner
dependency_groups = quality
allowlist_externals = make
commands =
    make quality-rst

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
allowlist_externals =
    make
    rm
    touch
commands =
    pylint edx_proctoring
    pycodestyle edx_proctoring
    isort --check-only --diff edx_proctoring manage.py

[testenv:version_check]
runner = uv-venv-lock-runner
dependency_groups = test
commands =
    python {toxinidir}/edx_proctoring/scripts/version_check.py

[testenv:pii_check]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups = test
allowlist_externals = make
commands =
    make pii_check

[pycodestyle]
exclude = .git,.tox,migrations
max-line-length = 120

[pydocstyle]
match-dir = (?!migrations)

[doc8]
max-line-length = 120

[testenv:translations]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups =
    django42: django42
    django52: test
allowlist_externals = make
commands =
    make validate_translations
