[tox]
envlist =
    celery{50}-django{42,52}-drflatest,
    quality,
    version_check,
    pii_check,
    translations-django{42,52}
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups =
    django42: django42
    django52: test
allowlist_externals = make
commands =
    make test-python PYTEST_ARGS="{posargs:-n 3}"

[testenv:js_tests]
runner = uv-venv-lock-runner
dependency_groups = dev
allowlist_externals =
    npm
    make
commands =
    npm install -g gulp-cli
    npm install
    make test-js

[testenv:js_lint]
runner = uv-venv-lock-runner
dependency_groups = dev
allowlist_externals =
    npm
    make
commands =
    npm install -g gulp-cli
    npm install
    make lint-js

[testenv:rst_validation]
runner = uv-venv-lock-runner
dependency_groups = quality
allowlist_externals = make
commands =
    make quality-rst

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
allowlist_externals = make
commands =
    make quality-python

[testenv:version_check]
runner = uv-venv-lock-runner
dependency_groups = test
commands =
    python {toxinidir}/src/edx_proctoring/scripts/version_check.py

[testenv:pii_check]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups = test
allowlist_externals = make
commands =
    make pii_check

[pycodestyle]
exclude = .git,.tox,migrations
max-line-length = 120

[pydocstyle]
; D101 = Missing docstring in public class
; D200 = One-line docstring should fit on one line with quotes
; D203 = 1 blank line required before class docstring
; D212 = Multi-line docstring summary should start at the first line
ignore = D101,D200,D202,D203,D204,D205,D210,D212,D400,D401,D404
match-dir = (?!migrations)

[doc8]
max-line-length = 120

[testenv:translations]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups =
    django42: django42
    django52: test
allowlist_externals = make
commands =
    make validate_translations
